import { UserDetail } from './user-detail';
import {User} from './user';

export const USERS_DETAILS: UserDetail[] = [
  { id: '1', age: 73, city: 'Somerset', info: 'Richard Hugh Blackmore (born 14 April 1945) is an English guitarist and songwriter. He was one of the founding members of Deep Purple in 1968, playing jam-style hard-rock music which mixed guitar riffs and organ sounds. During his solo career he established the heavy metal band Rainbow, which fused baroque music influences and elements of hard rock. Rainbow steadily moved to catchy pop-style mainstream rock. Later in life, he formed the traditional folk rock project Blackmore\'s Night, transitioning to vocalist-centred sounds. As a member of Deep Purple, Blackmore was inducted into the Rock and Roll Hall of Fame in April 2016.'},
  { id: '2', age: 68, city: 'Portsmouth',  info: 'Ronald James Padavona (July 10, 1942 – May 16, 2010), known professionally as Ronnie James Dio or simply Dio, was an American singer, songwriter, and musician. He fronted and/or founded numerous groups including Elf, Rainbow, Black Sabbath, Dio, and Heaven & Hell. He is credited with popularizing the "metal horns" hand gesture in metal culture and was known for his medieval-themed lyrics. Dio possessed a powerful, versatile vocal range, and was capable of singing both hard rock and lighter ballads.'},
  { id: '3', age: 41, city: 'New York',   info: 'John Gary Driscoll (18 April 1946 – 8 June 1987) was an American R&B-style rock drummer who performed in a number of successful bands from the 1960s until his death on June 10, 1987.[1][2] He first entered the music scene when he joined Ronnie Dio and The Prophets in June 1965, fronted by Ronnie James Dio. The band transformed into The Electric Elves, The Elves, and finally Elf in 1969, releasing a few singles along the way.'},
  { id: '4', age: 63, city: 'Florida',   info: 'Craig M. Gruber (June 15, 1951 – May 5, 2015)[2] was an American rock bassist, best known as the original bassist in Rainbow and most recently was a member for the band Zvekan. He also played in Elf, consisting of vocalist Ronnie James Dio, keyboardist Mickey Lee Soule, drummer Gary Driscoll and guitarist David Feinstein.'},
  { id: '5', age: 72, city: 'Manchester',   info: 'Micky Lee Soule (June 6, 1946 in Cortland, New York) is an American musician. He was the keyboard player for New York hard rock band Elf and a founding member of Rainbow.'}
];
